### ISSUE TITLE
 Error: Cannot find module 'simpl-schema' , in documentor.js

### ISSUE THREAD

**Issue by ideiudicibus** [Herteby/graphical-grapher#4]
Hi I've found this error:
Error: Cannot find module 'simpl-schema'

quickly browsing the code I believe this error can be solved in documentor.js

**Comment by Herteby** [comment]
I guess I assumed you already had simpl-schema installed. You need to install it like:
```
npm install --save simpl-schema
```

**Comment by ideiudicibus** [comment]
ok thanks got it
